<a href="https://colab.research.google.com/github/Byfroggy/AIpython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **08장 연습문제**

In [2]:
import matplotlib.pyplot as plt

In [3]:
import matplotlib.pyplot as plt
print(plt.rcParams['font.family'])

['sans-serif']


In [4]:
import matplotlib.pyplot as plt

plt.rcParams['font.family'] = 'sans-serif'  # 폰트 패밀리를 'sans-serif'로 설정
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Bitstream Vera Sans', 'Computer Modern Sans Serif', 'Lucida Grande', 'Verdana', 'Geneva', 'Lucid', 'Arial', 'Helvetica', 'sans-serif']  # 'sans-serif' 폰트 목록에서 'Arial'을 제외

1번

In [7]:
import numpy as np
print(np.__version__)

2.0.2


In [9]:
a = np.array([1,2,3])
print(a)

b = np.array([[1, 2], [3, 4]])
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [22]:
zeroList = np.zeros(5)
print(zeroList)

evenList = np.arange(2, 10, 2)
print(evenList)

mulA = np.array([2,4,6])
mulB = np.array([10,20,30])
print(mulA * mulB)

print((mulA * mulB)[mulA * mulB > 20])

[0. 0. 0. 0. 0.]
[2 4 6 8]
[ 20  80 180]
[ 80 180]


In [26]:
import pandas as pd

s = pd.Series([10,20,30,40])

data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [27]:
df.to_csv('output_students.csv', index=False)

In [31]:
df = pd.read_csv('train_and_test2.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [32]:
df.describe()

Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
25%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
50%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
75%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
max       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   

            Pclass  zero.15  zero.16     Embarked  zero.17  zero.18  \
count  1309.000000   1309.0   1309.0  1307.000000   1309.0   1309.0   
mean      2.294882      0.0      0.0     1.492731      0.0      0.0   
std       0.837836      0.0      0.0     0.814626      0.0      0.0   
min       1.000000      0.0      0.0     0.000000      0.0      0.0   
25%       2.000000      0.0      0.0     1.000000      0.0      0.0   
50%       3.000000      0.0      0.0     2.000000      0.0      0.0   
75%       3.000000      0.0      0.0     2.000000      0.0      0.0   
max       3.000000      0.0      0.0     2.000000      0.0      0.0   

          2urvived  
count  1309.000000  
mean      0.261268  
std       0.439494  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 28 columns]

In [33]:
df['Age']

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64

In [39]:
df[df['Age'] < 20]

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
7               8   2.0  21.0750    0      3     0       0       0       0   
9              10  14.0  30.0708    1      1     0       0       0       0   
10             11   4.0  16.7000    1      1     0       0       0       0   
14             15  14.0   7.8542    1      0     0       0       0       0   
16             17   2.0  29.1250    0      4     0       0       0       0   
...           ...   ...      ...  ...    ...   ...     ...     ...     ...   
1280         1281   6.0  21.0750    0      3     0       0       0       0   
1283         1284  13.0  20.2500    0      0     0       0       0       0   
1286         1287  18.0  60.0000    1      1     0       0       0       0   
1294         1295  17.0  47.1000    0      0     0       0       0       0   
1300         1301   3.0  13.7750    1      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
7          0  ...        0        0        0       3        0        0   
9          0  ...        0        0        0       2        0        0   
10         0  ...        0        0        0       3        0        0   
14         0  ...        0        0        0       3        0        0   
16         0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1280       0  ...        0        0        0       3        0        0   
1283       0  ...        0        0        0       3        0        0   
1286       0  ...        0        0        0       1        0        0   
1294       0  ...        0        0        0       1        0        0   
1300       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
7          2.0        0        0         0  
9          0.0        0        0         1  
10         2.0        0        0         1  
14         2.0        0        0         0  
16         1.0        0        0         0  
...        ...      ...      ...       ...  
1280       2.0        0        0         0  
1283       2.0        0        0         0  
1286       2.0        0        0         0  
1294       2.0        0        0         0  
1300       2.0        0        0         0  

[225 rows x 28 columns]

In [41]:
df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [42]:
result = df.groupby('Sex')['Age'].mean()
print(result)

Sex
0    30.017888
1    28.572082
Name: Age, dtype: float64
